<?php
$AREAS_PREDEFINIDAS = [
    'Admisión',
    'Administración',
    'Archivo Central',
    'Asesoría Legal - Secretaría General',
    'Asuntos académicos',
    'Biblioteca',
    'Bienes patrimoniales',
    'Bienestar Universitario',
    'Calidad Educativa y Acreditación',
    'Colocación Laboral',
    'Contabilidad y Finanzas',
    'Cosmiatría',
    'Decanatura de CCSS',
    'Decanatura de Ciencias empresariales y Derecho',
    'Defensoría Universitaria',
    'Docentes',
    'E.P. Administración',
    'E.P. Derecho',
    'E.P. Enfermería',
    'E.P. Estomatología',
    'E.P. Farmacia y Bioquímica',
    'E.P. Medicina',
    'E.P. Obstetricia',
    'E.P. Psicología',
    'Escuela de Postgrado',
    'Gerencia',
    'Informes',
    'Instituto de Investigación',
    'Laboratorio',
    'Limpieza',
    'Logística',
    'Mantenimiento',
    'Marketing',
    'Mesa de partes',
    'Otros',
    'Planeación',
    'Produccion de Bienes y Servicios',
    'Rectorado',
    'Registros académicos',
    'Talento Humano',
    'Tesorería',
    'TIC',
    'Vicerrectorado Académico',
    'Vigilancia'
];

$CARGOS_POR_AREA = [
    'Asesoría Legal - Secretaría General' => ['Asesor(a) Legal', 'Secretario General', 'Asistente de asesoría legal', 'Asistente de grados y títulos', 'Asistente de Secretaría General', 'Responsable de Grados y Títulos', 'Analista', 'Asistente', 'Especialista', 'Apoyo',  'Practicante'],
    'Archivo Central' => ['Responsable de archivo central', 'Asistente de archivo central', 'Apoyo', 'Especialista', 'Practicante'],
    'TIC' => ['Jefe de TIC', 'Asistente de TIC', 'Encargado de oficina de TIC', 'Apoyo', 'Practicante'],
    'Administración' => ['Director General de Administración', 'Responsable', 'Asistente de Dirección General de Administración', 'Apoyo', 'Practicante'],
    'Gerencia' => ['Gerente General', 'Asistente de Gerencia', 'Apoyo', 'Practicante', 'Secretaria'],
    'Defensoría Universitaria' => ['Jefe', 'Responsable', 'Docente TC', 'Asistente', 'Apoyo', 'Practicante'],
    'Rectorado' => ['Rector(a)', 'Asistente', 'Apoyo', 'Practicante'],
    'Vicerrectorado Académico' => ['Vicerrector(a)', 'Asistente', 'Apoyo', 'Practicante'],
    'Colocación Laboral' => ['Responsable de colocación laboral', 'Docente TC', 'Apoyo', 'Asistente', 'practicante'],
    'Decanatura de CCSS' => ['Decano(a)', 'Asistente', 'Apoyo', 'Practicante'],
    'Decanatura de Ciencias empresariales y Derecho' => ['Decano(a)', 'Asistente', 'Apoyo', 'Practicante'],
    'Docentes' => ['Docente TC', 'Docente TP', 'Docente Renacyt', 'Docente Ordinarizado', 'Jefe de práctica', 'Apoyo', 'Practicante'],
    'E.P. Obstetricia' => ['Director(a)', 'Coordinador(a)', 'Docente TC', 'Docente TP', 'Asistente', 'Apoyo', 'Practicante'],
    'E.P. Estomatología' => ['Director(a)', 'Coordinador(a)', 'Docente TC', 'Docente TP', 'Asistente', 'Apoyo', 'Practicante'],
    'E.P. Farmacia y Bioquímica' => ['Director(a)', 'Coordinador(a)', 'Docente TC', 'Docente TP', 'Asistente', 'Apoyo', 'Practicante'],
    'E.P. Medicina' => ['Director(a)', 'Coordinador(a)', 'Docente TC', 'Docente TP', 'Asistente', 'Apoyo', 'Practicante'],
    'E.P. Derecho' => ['Director(a)', 'Coordinador(a)', 'Docente TC', 'Docente TP', 'Asistente', 'Apoyo', 'Practicante'],
    'E.P. Psicología' => ['Director(a)', 'Coordinador(a)', 'Docente TC', 'Docente TP', 'Asistente', 'Apoyo', 'Practicante'],
    'E.P. Enfermería' => ['Director(a)', 'Coordinador(a)', 'Docente TC', 'Docente TP', 'Asistente', 'Apoyo', 'Practicante'],
    'E.P. Administración' => ['Director(a)', 'Coordinador(a)', 'Docente TC', 'Docente TP', 'Asistente', 'Apoyo', 'Practicante'],
    'Informes' => ['Jefe', 'Responsable', 'Asistente', 'Apoyo', 'Asesor(a)', 'Practicante'],
    'Tesorería' => ['Jefe', 'Encargado', 'Cajera', 'Asistente', 'Apoyo', 'Practicante'],
    'Contabilidad y Finanzas' => ['Jefe', 'Contador I', 'Contador II', 'Contador III', 'Responsable', 'Asistente', 'Auxiliar', 'Apoyo', 'Practicante'],
    'Escuela de Postgrado' => ['Director(a)', 'Coordinador(a)', 'Docente TC', 'Responsable', 'Asistente', 'Apoyo proveeduría', 'Asesora de ventas', 'Apoyo', 'Practicante'],
    'Instituto de Investigación' => ['Director', 'Coordinador', 'Docente TC', 'Responsable', 'Asistente', 'Apoyo', 'Practicante'],
    'Asuntos académicos' => ['Jefe', 'Responsable', 'Docente TC', 'Asistente', 'Apoyo', 'Practicante'],
    'Bienestar Universitario' => ['Jefe', 'Docente TC', 'Asistente', 'Responsable Deportes', 'Responsable Cultura', 'Responsable Psicopedagogico', 'Responsable de becas', 'Responsable de tópico', 'Asistente social', 'Apoyo', 'Practicante'],
    'Calidad Educativa y Acreditación' => ['Director', 'Coordinador', 'Docente TC', 'Especialista', 'Asistente', 'Apoyo', 'Practicante'],
    'Marketing' => ['Jefe', 'Responsable', 'Docente TC', 'Asistente', 'Gestor de contenido', 'Diseñador gráfico', 'Community Manager', 'Promotor de colegio', 'Telemarketing', 'Asesor', 'Apoyo', 'Practicante'],
    'Limpieza' => ['Jefe', 'Supervisor', 'Operario', 'Auxiliar', 'Apoyo'],
    'Talento Humano' => ['Jefe', 'Analista', 'Responsable', 'Asistente', 'Apoyo', 'Practicante'],
    'Producción de Bienes y Servicios' => ['Jefe', 'Responsable', 'Analista', 'Asesor', 'Asistente', 'Apoyo', 'Practicante'],
    'Logística' => ['Jefe', 'Responsable','Analista', 'Asistente', 'Apoyo', 'Practicante'],
    'Mantenimiento' => ['Jefe', 'Supervisor', 'Operario', 'Responsable de unidades dentales', 'Encargado de áreas verdes', 'Asistente', 'Apoyo'],
    'Vigilancia' => ['Jefe', 'Supervisor', 'Operario', 'Vigilante', 'Apoyo'],
    'Laboratorio' => ['Jefe', 'Analista', 'Responsable', 'Asistente', 'Apoyo', 'Practicante'],
    'Mesa de partes' => ['Jefe', 'Analista', 'Responsable', 'Asistente', 'Apoyo', 'Practicante'],
    'Registros académicos' => ['Jefe', 'Responsable', 'Docente TC', 'Asistente', 'Apoyo', 'Practicante'],
    'Biblioteca' => ['Jefe', 'Docente TC', 'Analista', 'Especialista', 'Responsable', 'Asistente', 'Apoyo', 'Practicante'],
    'Cosmiatría' => ['Jefe', 'Analista', 'Responsable', 'Docente', 'Asistente', 'Apoyo', 'Practicante'],
    'Admisión' => ['Jefe', 'Asistente', 'Responsable', 'Apoyo', 'Practicante'],
    'Planeación' => ['Jefe', 'Analista', 'Responsable', 'Asistente', 'Apoyo', 'Practicante'],
    'Bienes patrimoniales' => ['Jefe', 'Analista', 'Responsable', 'Asistente', 'Apoyo', 'Practicante']

];